spring:
  messages:
    basename: i18n/messages
  profiles:
    active: prod
  servlet:
    multipart:
      max-file-size: 2GB
      max-request-size: 2GB
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  application:
    name: video  #服务名称
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848 # nacos地址
      discovery:
          namespace: 180ff210-4b23-465c-a596-b52c751d2edc
server:
  port: 9000
aliyun:
  vod:
    file:
      keyid: LTAI5t993RxFv7iC7AcBWcaW
      keysecret: 5GduvEROBXuJ87qf0wH26olpIqhsqN




